service:
  host: 127.0.0.1
  port: 3000

mysql:
  host: 'localhost'
  port: 3306
  username: 'root'
  password: '123456'
  database: 'book_library'

jwt:
  accessSecretKey: '0~N3RbbP<#cIo55'
  accessTokenExpireIn: '1h'
  refreshSecretKey: 'LCY{r2l10~?)/qu'
  refreshTokenExpireIn: '4h'
